config/routes.rb
Bbb310::Application.routes.draw do
  resources :bars

  resources :genres

  resources :areas

end

app/models/area.rb
class Area < ActiveRecord::Base
  attr_accessible :description, :name
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  has_many :bars
end

app/models/bar.rb
class Bar < ActiveRecord::Base
  belongs_to :area
  belongs_to :genre
  attr_accessible :address, :closed_time, :description, :image_url, :name, :open_time, :telephone_number, :genre_id, :area_id, :genre, :area

  validates :name, presence: true, uniqueness: true
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true, uniqueness: true
  has_many :bars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @areas }
    end
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @area = Area.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/new
  # GET /areas/new.json
  def new
    @area = Area.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/1/edit
  def edit
    @area = Area.find(params[:id])
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(params[:area])

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render json: @area, status: :created, location: @area }
      else
        format.html { render action: "new" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /areas/1
  # PUT /areas/1.json
  def update
    @area = Area.find(params[:id])

    respond_to do |format|
      if @area.update_attributes(params[:area])
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area = Area.find(params[:id])
    @area.destroy

    respond_to do |format|
      format.html { redirect_to areas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  # GET /bars
  # GET /bars.json
  def index
    @bars = Bar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bars }
    end
  end

  # GET /bars/1
  # GET /bars/1.json
  def show
    @bar = Bar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/new
  # GET /bars/new.json
  def new
    @bar = Bar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/1/edit
  def edit
    @bar = Bar.find(params[:id])
  end

  # POST /bars
  # POST /bars.json
  def create
    @bar = Bar.new(params[:bar])

    respond_to do |format|
      if @bar.save
        format.html { redirect_to @bar, notice: 'Bar was successfully created.' }
        format.json { render json: @bar, status: :created, location: @bar }
      else
        format.html { render action: "new" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bars/1
  # PUT /bars/1.json
  def update
    @bar = Bar.find(params[:id])

    respond_to do |format|
      if @bar.update_attributes(params[:bar])
        format.html { redirect_to @bar, notice: 'Bar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy

    respond_to do |format|
      format.html { redirect_to bars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @genres }
    end
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
    @genre = Genre.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @genre }
    end
  end

  # GET /genres/new
  # GET /genres/new.json
  def new
    @genre = Genre.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @genre }
    end
  end

  # GET /genres/1/edit
  def edit
    @genre = Genre.find(params[:id])
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(params[:genre])

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render json: @genre, status: :created, location: @genre }
      else
        format.html { render action: "new" }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /genres/1
  # PUT /genres/1.json
  def update
    @genre = Genre.find(params[:id])

    respond_to do |format|
      if @genre.update_attributes(params[:genre])
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<h1>Listing areas</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @areas.each do |area| %>
  <tr>
    <td><%= area.name %></td>
    <td><%= area.description %></td>
    <td><%= link_to 'Show', area %></td>
    <td><%= link_to 'Edit', edit_area_path(area) %></td>
    <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @area.name %>
</p>

<p>
  <b>Description:</b>
  <%= @area.description %>
</p>


<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/bars/_form.html.erb
<%= form_for(@bar) do |f| %>
  <% if @bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bar.errors.count, "error") %> prohibited this bar from being saved:</h2>

      <ul>
      <% @bar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :telephone_number %><br />
    <%= f.text_field :telephone_number %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :open_time %><br />
    <%= f.time_select :open_time %>
  </div>
  <div class="field">
    <%= f.label :closed_time %><br />
    <%= f.time_select :closed_time %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :area %><br />
    <%= f.collection_select :area_id, Area.all, :id, :name, include_blank: true  %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: true  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bars/edit.html.erb
<h1>Editing bar</h1>

<%= render 'form' %>

<%= link_to 'Show', @bar %> |
<%= link_to 'Back', bars_path %>

app/views/bars/index.html.erb
<h1>Listing bars</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Telephone number</th>
    <th>Address</th>
    <th>Open time</th>
    <th>Closed time</th>
    <th>Image url</th>
    <th>Area</th>
    <th>Genre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bars.each do |bar| %>
  <tr>
    <td><%= bar.name %></td>
    <td><%= bar.description %></td>
    <td><%= bar.telephone_number %></td>
    <td><%= bar.address %></td>
    <td><%= bar.open_time %></td>
    <td><%= bar.closed_time %></td>
    <td><%= bar.image_url %></td>
    <td><%= bar.area.name %></td>
    <td><%= bar.genre.name %></td>
    <td><%= link_to 'Show', bar %></td>
    <td><%= link_to 'Edit', edit_bar_path(bar) %></td>
    <td><%= link_to 'Destroy', bar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bar', new_bar_path %>

app/views/bars/new.html.erb
<h1>New bar</h1>

<%= render 'form' %>

<%= link_to 'Back', bars_path %>

app/views/bars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bar.name %>
</p>

<p>
  <b>Description:</b>
  <%= @bar.description %>
</p>

<p>
  <b>Telephone number:</b>
  <%= @bar.telephone_number %>
</p>

<p>
  <b>Address:</b>
  <%= @bar.address %>
</p>

<p>
  <b>Open time:</b>
  <%= @bar.open_time %>
</p>

<p>
  <b>Closed time:</b>
  <%= @bar.closed_time %>
</p>

<p>
  <b>Image url:</b>
  <%= @bar.image_url %>
</p>

<p>
  <b>Area:</b>
  <%= @bar.area.name %>
</p>

<p>
  <b>Genre:</b>
  <%= @bar.genre.name %>
</p>


<%= link_to 'Edit', edit_bar_path(@bar) %> |
<%= link_to 'Back', bars_path %>

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<h1>Listing genres</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @genres.each do |genre| %>
  <tr>
    <td><%= genre.name %></td>
    <td><%= link_to 'Show', genre %></td>
    <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
    <td><%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Genre', new_genre_path %>

app/views/genres/new.html.erb
<h1>New genre</h1>

<%= render 'form' %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @genre.name %>
</p>


<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bbb310</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>